config/routes.rb
Rails.application.routes.draw do
 #get 'home/zipcode'
 root 'home#index'


get "/zipcode" => 'home#zipcode', as: 'zipcode'
post "/zipcode" => 'home#zipcode'
 #post "/home/zipcode" => 'home/zipcode'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'net/http'
  require 'json'

  def index
    @final_output, @api_color, @api_description = fetch_data('89129')
  end

  def zipcode
    @zip_query = params[:zipcode]

    if @zip_query.empty?
      @zip_query = "Hey you forgot to enter a zipcode!"
    else
      @final_output, @api_color, @api_description = fetch_data(@zip_query)
    end
  end

  private

  def fetch_data(zip_code)
    url = "https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=#{zip_code}&distance=10&API_KEY=C51870B1-64E2-47DB-A8D8-DCFAE583AA91"
    uri = URI(url)
    response = Net::HTTP.get(uri)
    output = JSON.parse(response)

    final_output = "Error"
    api_color = 'gray'
    api_description = ""

    unless output.empty?
      final_output = output[0]['AQI']

      case final_output
      when 0..50
        api_color = "green"
        api_description = "Good (0-50) Air quality is very good."
      when 51..100
        api_color = "yellow"
        api_description = "Moderate 51-100"
      when 101..150
        api_color = "orange"
        api_description = "Unhealthy for Sensitive Groups (USG) 101-150"
      when 151..200
        api_color = "red"
        api_description = "Unhealthy 151-200"
      when 201..300
        api_color = "purple"
        api_description = "Very Unhealthy 201-300"
      else
        api_color = "maroon"
        api_description = "Hazardous 301-500"
      end
    end

    [final_output, api_color, api_description]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-secondary">
  <div class="container">
    <%= link_to "MY OZONE", root_path, class: "navbar-brand" %>

    <!--<a class="navbar-brand" href="#">MY OZONE</a>-->
<div class="navbar-nav ms-auto">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= form_tag zipcode_path, method: :get, class: "nav-link" do %>
            <%= text_field_tag 'zipcode', nil, placeholder: "Search Zipcode", class: "form-control me-2" %>
            <%= submit_tag 'Search', class: "btn btn-outline-warning my-2 my-sm-0" %>
          <% end %>
        </li>
      </ul>
      </div>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4">OZONE - <%= @final_output %></h1>
  <p class="lead">This is the current ozone air quality readout for my neighborhood in Las Vegas.</p>
  <hr class="my-4">
  <p><%= @api_description %></p>
  </br>
</div>

</br>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4">OZONE -  <%= @final_output %></h1>
  <p class="lead">This is the current ozone air quality readout for the <%= @zip_query %> zipcode.</p>
  <hr class="my-4">
  <p><%= @api_description %></p>
  </br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class = "container">
      </br>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>